---
- name: 重启 TAI Service
  ansible.builtin.command: >-
    docker compose --env-file /opt/tai-deploy/tai-service/.env
    -p tai-tai-service -f /opt/tai-deploy/tai-service/compose.yml restart
  when: not ansible_check_mode
  changed_when: true
